### ISSUE TITLE
Error at loader - Cannot augment module

### ISSUE THREAD

**Issue by YannCaron** [troyedwardsjr/phaser3-typescript-webpack#5]
Another error I faced at startup (non blocking)

![screenshot from 2018-10-21 16-47-39](https://user-images.githubusercontent.com/5962300/47268446-6a763880-d551-11e8-897b-10e0be86f534.png)

**Comment by YannCaron** [comment]
For information, this error come from the new version of nodejs (10.12.0)
To be evaluated if it is a nodejs error or some not supported package properties.

**Comment by troyedwardsjr** [comment]
Try removing `@types/node` in the `node_modules` folder and see what happens.

**Comment by troyedwardsjr** [comment]
@YannCaron Actually I just set `allowSyntheticDefaultImports` to `true` in the `tsconfig.json`. So pull from the latest and see if that helps.

**Comment by YannCaron** [comment]
I've resolved this issue by downgrading nodeJs to version 8
It works fine.

**Comment by YannCaron** [comment]
Many thanks for your help @troyedwardsjr
